version: "3.5"
networks:
  default:
    name: zkevm
services:
  zkevm-pool-manager:
    container_name: zkevm-pool-manager
    restart: unless-stopped
    depends_on:
      zkevm-pool-db:
        condition: service_healthy
    image: zkevm-pool-manager
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    ports:
      - 8545:8545
    volumes:
      - ./test/config/test.poolmanager.toml:/app/poolmanager.toml:ro

  zkevm-pool-db:
    container_name: zkevm-pool-db
    restart: unless-stopped
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command:
      - "postgres"
      - "-N"
      - "500"

  cdk-erigon:
      container_name: cdk-erigon
      image: hermeznetwork/cdk-erigon:latest
      ports:
        - 8467:8467
      volumes:
        - ./data/cdk-erigon:/data/cdk-erigon
        - ./test/config/test.cdk.erigon.yaml:/test.cdk.erigon.yaml
      environment:
        - CDK_ERIGON_SEQUENCER=1        
      command: >
        --config="/test.cdk.erigon.yaml" --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=*
