// Code generated by mockery v2.39.0. DO NOT EDIT.

package server

import (
	db "github.com/0xPolygonHermez/zkevm-pool-manager/db"
	mock "github.com/stretchr/testify/mock"
)

// monitorMock is an autogenerated mock type for the monitorInterface type
type monitorMock struct {
	mock.Mock
}

// AddL2Transaction provides a mock function with given fields: l2Tx
func (_m *monitorMock) AddL2Transaction(l2Tx *db.L2Transaction) {
	_m.Called(l2Tx)
}

// newMonitorMock creates a new instance of monitorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMonitorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *monitorMock {
	mock := &monitorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
