// Code generated by mockery v2.39.0. DO NOT EDIT.

package server

import (
	context "context"

	types "github.com/0xPolygonHermez/zkevm-pool-manager/types"
	mock "github.com/stretchr/testify/mock"
)

// poolDBMock is an autogenerated mock type for the poolDBInterface type
type poolDBMock struct {
	mock.Mock
}

// AddL2Transaction provides a mock function with given fields: ctx, tx
func (_m *poolDBMock) AddL2Transaction(ctx context.Context, tx *types.L2Transaction) (uint64, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for AddL2Transaction")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.L2Transaction) (uint64, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.L2Transaction) uint64); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.L2Transaction) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateL2TransactionStatus provides a mock function with given fields: ctx, id, newStatus, errorMsg
func (_m *poolDBMock) UpdateL2TransactionStatus(ctx context.Context, id uint64, newStatus string, errorMsg string) error {
	ret := _m.Called(ctx, id, newStatus, errorMsg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateL2TransactionStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string, string) error); ok {
		r0 = rf(ctx, id, newStatus, errorMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newPoolDBMock creates a new instance of poolDBMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newPoolDBMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *poolDBMock {
	mock := &poolDBMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
