// Code generated by mockery v2.39.0. DO NOT EDIT.

package server

import (
	context "context"

	db "github.com/0xPolygonHermez/zkevm-pool-manager/db"
	mock "github.com/stretchr/testify/mock"
)

// poolDBMock is an autogenerated mock type for the poolDBInterface type
type poolDBMock struct {
	mock.Mock
}

// AddTx provides a mock function with given fields: ctx, tx
func (_m *poolDBMock) AddTx(ctx context.Context, tx db.Transaction) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for AddTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.Transaction) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newPoolDBMock creates a new instance of poolDBMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newPoolDBMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *poolDBMock {
	mock := &poolDBMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
